services:
  backend:
    build:
      context: ./backend
    container_name: reviewgen-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - default
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=api.review-gen.ringscaleai.com
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=api.review-gen.ringscaleai.com

  frontend:
    build:
      context: ./frontend
    container_name: reviewgen-frontend
    ports:
      - "3008:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - default
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=review-gen.ringscaleai.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=review-gen.ringscaleai.com

networks:
  nginx-proxy:
    external: true